title: Evolution of Taoism
description: From a disorganized philosophy to an organized religion
show_downloads: false
google_analytics:
author_name: Dev Singh
theme: jekyll-theme-dinky
markdown: kramdown
redcarpet:
  extensions: ["superscript"]
